# Generated by Django 5.1.7 on 2025-03-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', '🔥 สูง'), ('medium', '⚡ ปานกลาง'), ('low', '✅ ต่ำ')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
